### ISSUE TITLE
Implement Object::GetRealNamedProperty() and friends

### ISSUE THREAD

**Issue by ehsan** [mozilla/spidernode#74]
I looked a bit into this, and here is a rough summary of what I have found out so far.  It seems like in V8, there may be objects in the prototype chain that are for interception only, and GetRealNamedProperty() traverses the prototype chain skipping those types of objects.

I haven't yet figured out how to emulate this on top of SpiderMonkey...

**Comment by tbsaunde** [comment]
looks like chakrashim just ignores interceptors, so that may be an option.  However its not obvious to me that is correct even if you only care about node.
Otherwise this seems pretty related to ObjectTemplate::SetNamedPropertyHandler() I guess that's the? at least a way of setting up interceptors.  So probably best for bz to look at this with the other ObjectTemplate stuff.
